// Offline renderer for the logged-out scrollytelling drone shot.
//
// Drives the ported three.js scene (scene.html) in real headless-Chrome WebGL
// and writes a WebP frame sequence to assets/scrollytelling/frames/. The app
// plays those frames back as scroll-driven <Image>s, sidestepping the expo-gl
// on-device surface-presentation bug entirely.
//
// Usage: node scripts/render-scrollytelling/render.mjs [frames] [width] [height]

import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import puppeteer from 'puppeteer-core';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const APP_ROOT = path.resolve(__dirname, '../..');
const OUT_DIR = path.join(APP_ROOT, 'assets/scrollytelling/frames');

const FRAMES = Number(process.argv[2]) || 144;
const WIDTH = Number(process.argv[3]) || 900;
const HEIGHT = Number(process.argv[4]) || 1600;

const CHROME =
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';

const MIME = {
  '.html': 'text/html',
  '.js': 'text/javascript',
  '.mjs': 'text/javascript',
  '.glb': 'model/gltf-binary',
  '.wasm': 'application/wasm',
};

// Static file server rooted at the app dir so /node_modules/three/... and
// /assets/models/*.glb resolve, plus /scene.html from this script's folder.
function startServer() {
  const server = http.createServer((req, res) => {
    let urlPath = decodeURIComponent(req.url.split('?')[0]);
    let filePath;
    if (urlPath === '/scene.html' || urlPath === '/') {
      filePath = path.join(__dirname, 'scene.html');
    } else {
      filePath = path.join(APP_ROOT, urlPath);
    }
    fs.readFile(filePath, (err, data) => {
      if (err) {
        res.writeHead(404);
        res.end('not found: ' + urlPath);
        return;
      }
      res.writeHead(200, { 'Content-Type': MIME[path.extname(filePath)] || 'application/octet-stream' });
      res.end(data);
    });
  });
  return new Promise((resolve) => server.listen(0, () => resolve(server)));
}

async function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  for (const f of fs.readdirSync(OUT_DIR)) fs.rmSync(path.join(OUT_DIR, f));

  const server = await startServer();
  const port = server.address().port;
  const url = `http://localhost:${port}/scene.html?w=${WIDTH}&h=${HEIGHT}`;

  const browser = await puppeteer.launch({
    executablePath: CHROME,
    headless: 'new',
    args: [
      '--use-gl=angle',
      '--use-angle=metal',
      '--enable-webgl',
      '--ignore-gpu-blocklist',
      '--no-sandbox',
    ],
  });

  const page = await browser.newPage();
  await page.setViewport({ width: WIDTH, height: HEIGHT, deviceScaleFactor: 1 });
  page.on('console', (m) => console.log('  [page]', m.text()));
  page.on('pageerror', (e) => console.log('  [pageerror]', e.message));

  await page.goto(url, { waitUntil: 'networkidle0', timeout: 60000 });

  await page.waitForFunction('window.__ready === true || window.__error', { timeout: 60000 });
  const pageError = await page.evaluate('window.__error || null');
  if (pageError) throw new Error('scene boot failed: ' + pageError);

  console.log(`Rendering ${FRAMES} frames at ${WIDTH}x${HEIGHT} ...`);
  for (let i = 0; i < FRAMES; i += 1) {
    const progress = FRAMES === 1 ? 0 : i / (FRAMES - 1);
    const dataUrl = await page.evaluate((p) => window.renderFrame(p), progress);
    const base64 = dataUrl.replace(/^data:image\/webp;base64,/, '');
    const name = `frame_${String(i).padStart(3, '0')}.webp`;
    fs.writeFileSync(path.join(OUT_DIR, name), Buffer.from(base64, 'base64'));
    if (i % 20 === 0 || i === FRAMES - 1) console.log(`  ${i + 1}/${FRAMES}`);
  }

  await browser.close();
  server.close();

  const files = fs.readdirSync(OUT_DIR).filter((f) => f.endsWith('.webp')).sort();
  const bytes = files.reduce((n, f) => n + fs.statSync(path.join(OUT_DIR, f)).size, 0);

  // Emit a static manifest. Metro only bundles assets referenced by literal
  // require() paths, so every frame is spelled out here rather than globbed.
  const requires = files.map((f) => `  require('./frames/${f}'),`).join('\n');
  const manifest = `// AUTO-GENERATED by scripts/render-scrollytelling/render.mjs — do not edit.
// The pre-rendered drone-shot frame sequence for the logged-out scrollytelling.
export const FRAME_WIDTH = ${WIDTH};
export const FRAME_HEIGHT = ${HEIGHT};
export const FRAMES = [
${requires}
];
`;
  fs.writeFileSync(path.join(path.dirname(OUT_DIR), 'frames.generated.js'), manifest);

  console.log(`Done. ${files.length} frames, ${(bytes / 1e6).toFixed(2)} MB total.`);
  console.log(`Manifest: assets/scrollytelling/frames.generated.js`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
